### ISSUE TITLE
Iteration Two: download the datasets and add them to our filesystem

### ISSUE THREAD

**Issue by podoglyph** [rongxanh88/bike-share#16]

**Comment by podoglyph** [comment]
I have them in my local filesystem. Atom isn't recognizing them in the filetree, but using terminal I can see that they are in the db/csv directory.

**Comment by rongxanh88** [comment]
Can everyone confirm that they can access and see the files in the proper directory? Then we can move this to done.

**Comment by carlrc** [comment]
Done.
